---
sudo: required
language: python
services:
  - docker

install:
  - pip install -r requirements.txt

script:
  - molecule --version
  - ansible --version
  - molecule test -s default
  - molecule test -s with-server

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
