---
- hosts: all
  pre_tasks:
    - name: "Installing packages on CentOS"
      yum:
        name: "{{ item }}"
        state: installed
      with_items:
        - net-tools
        - which
      when: ansible_distribution == 'CentOS'
    - name: "Installing packages on NON-CentOS"
      apt:
        name: "{{ item }}"
        state: installed
      with_items:
        - net-tools
      when: ansible_distribution != 'CentOS'
  roles:
    - role: ansible-zabbix-agent
      zabbix_agent_server: 192.168.3.33
      zabbix_agent_serveractive: 192.168.3.33
      zabbix_agent_listenip: 0.0.0.0
