---
# tasks file for wdijkerman.zabbix

- name: "Install the correct repository"
  include: "RedHat.yml"
  when: ansible_os_family == "RedHat"

- name: "Install the correct repository"
  include: "Debian.yml"
  when: ansible_os_family == "Debian"

- name: "Install the correct repository"
  include: "Suse.yml"
  when: ansible_os_family == "Suse"

- name: "Fail invalid specified agent_listeninterface"
  fail:
    msg: "The specified network interface does not exist"
  when: "agent_listeninterface and (agent_listeninterface not in ansible_interfaces)"
  tags:
    - config

- name: "Get IP of agent_listeninterface when no agent_listenip specified"
  set_fact:
    agent_listenip: "{{ hostvars[inventory_hostname]['ansible_' + agent_listeninterface]['ipv4'].address | default('0.0.0.0') }}"
  when: "agent_listeninterface and not agent_listenip"
  tags:
    - config

- name: "Default agent_listenip to all when not specified"
  set_fact:
    agent_listenip: '0.0.0.0'
  when: "not agent_listenip"
  tags:
    - config

- name: "Fail invalid specified agent_listenip"
  fail:
    msg: "The agent_listenip does not exist"
  when: "agent_listenip != '0.0.0.0' and agent_listenip not in ansible_all_ipv4_addresses"
  tags:
    - config

- name: "Configure zabbix-agent"
  template: src=zabbix_agentd.conf.j2
            dest=/etc/zabbix/zabbix_agentd.conf
            owner=zabbix
            group=zabbix
            mode=0755
  notify: restart zabbix-agent
  sudo: yes
  tags:
    - config
    - init

- name: "Create include dir zabbix-agent"
  file: path={{ agent_include }}
        owner=zabbix
        group=zabbix
        state=directory
  sudo: yes
  tags:
    - config
    - include

- name: "Create hostgroups"
  local_action:
    module: zabbix_group
    server_url: "{{ zabbix_url }}"
    login_user: "{{ zabbix_api_user }}"
    login_password: "{{ zabbix_api_pass }}"
    host_groups: "{{ zabbix_host_groups }}"
    state: "{{ zabbix_create_hostgroup }}"
  when: zabbix_api_use == True
  tags:
    - api

- name: "Create a new host or update an existing host's info"
  local_action:
    module: zabbix_host
    server_url: "{{ zabbix_url }}"
    login_user: "{{ zabbix_api_user }}"
    login_password: "{{ zabbix_api_pass }}"
    host_name: "{{ ansible_fqdn }}"
    host_groups: "{{ zabbix_host_groups }}"
    link_templates: "{{  zabbix_link_templates }}"
    status: "{{ zabbix_host_status }}"
    state: "{{ zabbix_create_host }}"
    interfaces:
      - type: 1
        main: 1
        useip: "{{ zabbix_useuip }}"
        ip: "{{ hostvars[inventory_hostname]['ansible_'+ agent_listeninterface]['ipv4'].address }}"
        dns: "{{ ansible_fqdn }}"
        port: "{{ agent_listenport }}"
  when: zabbix_api_use == True
  tags:
    - api

- name: "Updating host configuration with macros"
  local_action:
    module: zabbix_hostmacro
    server_url: "{{ zabbix_url }}"
    login_user: "{{ zabbix_api_user }}"
    login_password: "{{ zabbix_api_pass }}"
    host_name: "{{ ansible_fqdn }}"
    macro_name: "{{ item.macro_key }}"
    macro_value: "{{ item.macro_value }}"
  with_items: zabbix_macros
  when: zabbix_api_use == True and zabbix_macros is defined and item.macro_key is defined
  tags:
    - api

