---
# Tasks specific for OpenSuse Systems

- name: "Suse | Set some facts"
  set_fact:
      zabbix_agent: "zabbix-agentd"
  set_fact: 
      zabbix_agent_service: "zabbix-agentd"
  tags:
    - zabbix-agent
    - init

- name: "Suse | Install basic repo file"
  zypper_repository: repo="http://download.opensuse.org/repositories/server:monitoring/openSUSE_{{ ansible_distribution_version }}/server:monitoring.repo"
  when: zabbix_repo == "zabbix"
  sudo: yes
  tags:
    - zabbix-agent
    - init

- name: "Suse | Install zabbix-agent"
  zypper: name={{ zabbix_agent_package }}
          state={{ zabbix_agent_package_state }}
          disable_gpg_check=yes
  sudo: yes
  tags:
    - zabbix-agent
    - init

