---

- name: "Installing user-defined userparameters"
  template:
    src: "userparameters/{{ item }}.j2"
    dest: "{{ zabbix_agent_include }}/userparameter_{{ item }}.conf"
    owner: zabbix
    group: zabbix
    mode: 0644
  notify: restart zabbix-agent
  become: yes
  with_items: "{{ zabbix_agent_userparameters }}"

- name: "Installing user-defined scripts"
  copy:
    src: "scripts/{{ item }}"
    dest: "/etc/zabbix/scripts/{{ item }}"
    owner: zabbix
    group: zabbix
    mode: 0644
  notify: restart zabbix-agent
  become: yes
  with_items: "{{ zabbix_agent_userparameters }}"
  when: zabbix_agent_custom_scripts
